# @package _global_

defaults:
  - pointnav_base
  - /habitat/dataset/pointnav: hm3d
  - _self_

habitat:
  environment:
    max_episode_steps: 500000
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 512
            height: 512
